version: "1.0"
info:
  model: int-scaffold
packages:
- name: SIQA_GIT_2109Project
  gitServerName: rimaSCName
  gitUrl: https://github.com/rimabarman
  gitUsername: rimabarman
  gitBranch: main
services:
- serviceName: project.siqa_git_2109.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.operations.actions:DBInsertNew
  packages:
  - name: SIQA_GIT_2109Project
    version: "1.0"
- serviceName: project.siqa_git_2109.integrations:SIQAAdapterFlow
  packages:
  - name: SIQA_GIT_2109Project
    version: "1.0"
